### ISSUE TITLE
Pip下载时候有这个error?

### ISSUE THREAD

**Issue by Holopie** [SummerColdWind/Indefinite-length-text-recognition#1]
ERROR: httpie from git+https://github.com/SummerColdWind/Indefinite-length-text-recognition.git#egg=httpie does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by SummerColdWind** [comment]
Because I didn't put this immature work in PYPI. Maybe you can try to clone the project directly to the local area and use it.
